import QRCode from 'qrcode'
import { colors as c } from '../data/designTokens'
import { cover } from './imageProcessor'

export type BuilderData = { name: string; build: string; stack: string; meet: string; bring: string; care: string; id: string; title: string; photo?: HTMLImageElement }
const W = 720, H = 1130, pad = 26

function canvas() { const el = document.createElement('canvas'); el.width = W * 2; el.height = H * 2; const ctx = el.getContext('2d')!; ctx.scale(2, 2); return [el, ctx] as const }
function type(ctx: CanvasRenderingContext2D, str: string, x: number, y: number, size: number, color = c.text, font = 'Arial', align: CanvasTextAlign = 'left') { ctx.fillStyle = color; ctx.font = `700 ${size}px ${font}`; ctx.textAlign = align; ctx.fillText(str, x, y) }
function wrap(ctx: CanvasRenderingContext2D, str: string, x: number, y: number, max: number, size: number, color = c.text, lh = 1.18) { ctx.font = `500 ${size}px Arial`; ctx.fillStyle = color; ctx.textAlign = 'left'; const words = (str || '—').split(/\s+/); let line = '', yy = y; for (const word of words) { if (ctx.measureText(`${line} ${word}`).width > max && line) { ctx.fillText(line, x, yy); yy += size * lh; line = word } else line += `${line ? ' ' : ''}${word}` } ctx.fillText(line, x, yy); return yy }
function star(ctx: CanvasRenderingContext2D, x: number, y: number, r = 18) { ctx.save(); ctx.translate(x,y); ctx.fillStyle = c.accent; ctx.beginPath(); for(let i=0;i<16;i++){const a=-Math.PI/2+i*Math.PI/8, rr=i%2?r*.27:r; const px=Math.cos(a)*rr,py=Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();ctx.restore() }
function shell(ctx: CanvasRenderingContext2D) { ctx.fillStyle = c.primary; ctx.fillRect(0,0,W,H); ctx.strokeStyle=c.cream;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(9,9,W-18,H-18,31);ctx.stroke();ctx.strokeStyle=c.secondary;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(29,29,W-58,H-58,20);ctx.stroke(); ctx.fillStyle='#020b07';ctx.strokeStyle=c.cream;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(W/2-67,45,134,30,16);ctx.fill();ctx.stroke(); star(ctx,52,53,19);star(ctx,W-52,53,19) }
function footer(ctx: CanvasRenderingContext2D) { const y=H-58;ctx.fillStyle=c.dark;ctx.fillRect(12,y,W-24,45); for(let x=20;x<W-20;x+=34){ctx.strokeStyle=c.secondary;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y+22);ctx.lineTo(x+12,y+8);ctx.lineTo(x+24,y+22);ctx.lineTo(x+12,y+37);ctx.closePath();ctx.stroke();ctx.strokeStyle=c.accent;ctx.strokeRect(x+7,y+17,10,10)} }
function palms(ctx: CanvasRenderingContext2D) { ctx.fillStyle='#064223';ctx.beginPath();ctx.moveTo(0,500);ctx.quadraticCurveTo(150,430,260,500);ctx.lineTo(300,730);ctx.lineTo(0,730);ctx.fill();ctx.fillStyle='#0b6037';ctx.beginPath();ctx.moveTo(0,620);ctx.quadraticCurveTo(150,540,300,640);ctx.lineTo(360,760);ctx.lineTo(0,760);ctx.fill(); for (const x of [55,155,570,650]) {ctx.strokeStyle=c.dark;ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(x,600);ctx.quadraticCurveTo(x+20,480,x-25,390);ctx.stroke();ctx.fillStyle=c.dark;for(let a=0;a<7;a++){ctx.save();ctx.translate(x-25,390);ctx.rotate(a*.9);ctx.beginPath();ctx.ellipse(0,-42,8,46,0,0,7);ctx.fill();ctx.restore()}} }
function line(ctx: CanvasRenderingContext2D, y: number) {ctx.strokeStyle=c.secondary;ctx.setLineDash([5,5]);ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(55,y);ctx.lineTo(W-55,y);ctx.stroke();ctx.setLineDash([])}

export async function renderFront(data: BuilderData) { const [el,ctx]=canvas(); shell(ctx); palms(ctx); type(ctx,'2:47',42,68,38,c.secondary);type(ctx,'PM',137,68,17,c.secondary);type(ctx,'STUDIO',42,101,19,c.accent); type(ctx,'HACKER',W/2,265,108,c.secondary,'Georgia','center');type(ctx,'HOUSE',W/2,430,108,c.secondary,'Georgia','center');type(ctx,'गोवा',W/2,308,57,c.accent,'serif','center');line(ctx,453); type(ctx,'GOA, INDIA',150,492,25,c.secondary);star(ctx,319,482,7);type(ctx,'28 – 31 OCT 2026',347,492,25,c.secondary)
  // sunset and user portrait medallion
  ctx.fillStyle=c.secondary;ctx.beginPath();ctx.arc(558,635,54,0,Math.PI*2);ctx.fill();ctx.fillStyle=c.dark;for(let i=0;i<7;i++){ctx.fillRect(500+i*15,687+i%2*7,110-i*25,4)}
  ctx.save();ctx.beginPath();ctx.arc(360,634,101,0,Math.PI*2);ctx.clip();if(data.photo) cover(ctx,data.photo,259,533,202,202);else {ctx.fillStyle=c.cream;ctx.fillRect(259,533,202,202);ctx.fillStyle=c.primary;ctx.beginPath();ctx.arc(360,600,28,0,7);ctx.fill();ctx.beginPath();ctx.arc(360,693,60,Math.PI,0);ctx.fill()}ctx.restore();ctx.strokeStyle=c.secondary;ctx.lineWidth=3;ctx.beginPath();ctx.arc(360,634,102,0,7);ctx.stroke();
  ctx.fillStyle=c.cream;ctx.fillRect(10,760,W-20,300); ctx.fillStyle=c.primary;ctx.fillRect(70,796,160,160);ctx.strokeStyle=c.accent;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(62,786,176,180,12);ctx.stroke();const qr=await QRCode.toDataURL(data.id,{margin:1,width:220,color:{dark:c.primary,light:c.cream}}); const qi=new Image();qi.src=qr;await qi.decode();ctx.drawImage(qi,76,802,148,148);type(ctx,'SCAN TO CONNECT',50,938,15,c.accent,'Arial','center');type(ctx,data.name.toUpperCase()||'YOUR NAME',270,830,33,c.primary);type(ctx,data.title,270,871,22,c.accent);ctx.fillStyle=c.dark;ctx.beginPath();ctx.roundRect(270,893,270,44,16);ctx.fill();type(ctx,data.id,405,924,20,c.secondary,'Arial','center');type(ctx,'BUILDER ID',405,963,16,c.primary,'Arial','center');line(ctx,986);type(ctx,'BUILD  •  SHIP  •  PARTY  •  REPEAT',360,1024,18,c.primary,'Arial','center');footer(ctx);return el }

function section(ctx: CanvasRenderingContext2D, icon: string, heading: string, value: string, x: number, y: number, max=265) {type(ctx,icon,x,y,40,c.accent);type(ctx,heading,x+72,y-2,25,c.secondary);wrap(ctx,value,x+72,y+40,max,20,c.cream);}
export function renderBack(data: BuilderData) {const [el,ctx]=canvas();shell(ctx);type(ctx,'FIND YOUR PEOPLE',W/2,172,49,c.secondary,'Arial','center');type(ctx,'You’re not just attending.',W/2,225,24,c.cream,'Arial','center');type(ctx,'You’re connecting.',W/2,261,24,c.cream,'Arial','center');ctx.strokeStyle=c.accent;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(150,247);ctx.lineTo(235,247);ctx.moveTo(485,247);ctx.lineTo(570,247);ctx.stroke();ctx.strokeStyle=c.secondary;ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(360,305);ctx.lineTo(360,838);ctx.stroke();ctx.setLineDash([]);section(ctx,'</>', 'I BUILD',data.build,58,350);section(ctx,'♧','I WANT TO MEET',data.meet,395,350,220);line(ctx,498);section(ctx,'ϟ','MY STACK',data.stack,58,566);section(ctx,'♙','I BRING',data.bring,395,566,220);line(ctx,674);section(ctx,'♡','I CARE ABOUT',data.care,58,745);section(ctx,'⌖','LOCATION','GOA, INDIA\n15.4909° N, 73.8278° E',395,745,220);line(ctx,850);type(ctx,'CONNECT. COLLABORATE. CODE IN PARADISE.',W/2,894,18,c.secondary,'Arial','center');type(ctx,'#HHGOA2026',W/2,963,42,c.accent,'Arial','center');type(ctx,'♥     ◎     ♣     in',W/2,1028,31,c.secondary,'Arial','center');footer(ctx);return el}

export async function renderSheet(data: BuilderData) {const front=await renderFront(data),back=renderBack(data);const out=document.createElement('canvas');out.width=front.width+back.width+80;out.height=Math.max(front.height,back.height);const ctx=out.getContext('2d')!;ctx.fillStyle='#060b08';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(front,0,0);ctx.drawImage(back,front.width+80,0);return out}
