import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { renderBack, renderFront, renderSheet, BuilderData } from './engine/canvasRenderer'
import { loadPhoto } from './engine/imageProcessor'
import { makeBuilderId, makeTitle } from './utils/builder'

type Form = Omit<BuilderData, 'id' | 'title' | 'photo'>
const initial: Form = { name: '', build: '', stack: '', meet: '', bring: '', care: '' }
const caption = 'Just found my people at Hacker House Goa 2026. Building, shipping and connecting in Goa. #FrameInGoa #HHGOA2026'

export default function App() {
  const [started,setStarted]=useState(false), [form,setForm]=useState<Form>(initial), [photo,setPhoto]=useState<HTMLImageElement>(), [fileName,setFileName]=useState(''), [generating,setGenerating]=useState(false), [cards,setCards]=useState<{front:string;back:string;sheet:string}>()
  const data = useMemo<BuilderData>(()=>({...form,photo,id:makeBuilderId(form.name),title:makeTitle(form.build,form.stack)}),[form,photo])
  useEffect(()=>{ if(!cards) return; const run=async()=>setCards({front:(await renderFront(data)).toDataURL('image/png'),back:(await renderBack(data)).toDataURL('image/png'),sheet:(await renderSheet(data)).toDataURL('image/png')}); const timer=setTimeout(run,100);return()=>clearTimeout(timer) },[form,photo])
  const update=(key:keyof Form)=>(e:ChangeEvent<HTMLInputElement>)=>setForm(f=>({...f,[key]:e.target.value}))
  const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try {setPhoto(await loadPhoto(file));setFileName(file.name)} catch {alert('We could not read this image. Try a JPG, PNG, or a browser-supported HEIC file.')}}
  const generate=async()=>{if(!form.name.trim()||!photo){alert('Add your name and photo to build your ID.');return}setGenerating(true);await new Promise(r=>setTimeout(r,480));const front=await renderFront(data),back=await renderBack(data),sheet=await renderSheet(data);setCards({front:front.toDataURL('image/png'),back:back.toDataURL('image/png'),sheet:sheet.toDataURL('image/png')});setGenerating(false)}
  const download=()=>{if(!cards)return;const a=document.createElement('a');a.href=cards.sheet;a.download=`HHGOA2026-${data.id}.png`;a.click()}
  if (!started) return <main className="landing"><div className="corner-star">✦</div><p className="eyebrow">HACKER HOUSE GOA 2026</p><h1>FIND YOUR<br/><em>PEOPLE</em></h1><p className="intro">Create your builder identity.<br/>Then find your people in paradise.</p><button className="gold" onClick={()=>setStarted(true)}>START BUILDING <span>→</span></button><div className="palm-art">☼<span>♣</span></div><p className="footer-copy">GOA, INDIA &nbsp;•&nbsp; 28–31 OCT 2026</p></main>
  return <main className="app-shell"><header><a onClick={()=>{setCards(undefined);setStarted(false)}}>HH<span>//</span>GOA</a><p>BUILDER IDENTITY GENERATOR</p></header>{!cards ? <section className="builder"><div className="form-heading"><p className="eyebrow">HACKER HOUSE GOA 2026</p><h1>FIND YOUR PEOPLE.</h1><p>Your builder card, in one quick pass.</p></div><div className="form-grid"><label className="upload"><input type="file" accept="image/jpeg,image/png,image/heic,image/heif" onChange={upload}/><b>{photo?'PHOTO READY':'01 / UPLOAD YOUR PHOTO'}</b><span>{photo ? fileName : 'JPG, PNG or HEIC • Any orientation'}</span>{photo&&<img src={photo.src}/>}</label><div className="fields"><Field label="02 / WHO ARE YOU?" placeholder="Your name" value={form.name} onChange={update('name')}/><Field label="03 / WHAT DO YOU BUILD?" placeholder="Developer tools, products, experiments…" value={form.build} onChange={update('build')}/><div className="two"><Field label="MY STACK / ROLE" placeholder="Rust / React" value={form.stack} onChange={update('stack')}/><Field label="I WANT TO MEET" placeholder="Builders, designers…" value={form.meet} onChange={update('meet')}/></div><div className="two"><Field label="WHAT I BRING" placeholder="Systems thinking" value={form.bring} onChange={update('bring')}/><Field label="I CARE ABOUT" placeholder="Open source" value={form.care} onChange={update('care')}/></div></div></div><button className="gold generate" onClick={generate} disabled={generating}>{generating?'BUILDING YOUR IDENTITY…':'GENERATE MY BUILDER CARD'} <span>→</span></button>{generating&&<div className="status">PHOTO <b>OK</b>　 BUILDER ID <b>OK</b>　 LAYOUT <b>READY</b></div>}</section> : <section className="result"><div className="result-head"><p className="eyebrow">YOUR BUILDER IDENTITY</p><h1>WELCOME TO THE HOUSE, {form.name.split(' ')[0].toUpperCase()}.</h1><p>Download your two-sided card or share the moment.</p></div><div className="cards"><figure><img src={cards.front} alt="Builder card front"/><figcaption>FRONT / BUILDER ID</figcaption></figure><figure><img src={cards.back} alt="Builder card back"/><figcaption>BACK / FIND YOUR PEOPLE</figcaption></figure></div><div className="actions"><button className="gold" onClick={download}>DOWNLOAD CARD ↓</button><a className="outline" href={`https://x.com/intent/post?text=${encodeURIComponent(caption)}`} target="_blank" rel="noreferrer">SHARE ON X ↗</a><button className="text-button" onClick={()=>setCards(undefined)}>START AGAIN</button></div><p className="share-note">X opens with the caption prefilled; attach the downloaded PNG from your device to include the image.</p></section>}</main>
}
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="field"><span>{label}</span><input {...props}/></label>}
